services:
  generator-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sports-generator-api
    ports:
      - "${CONTAINER_PORT:-5001}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - sports-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sports-network:
    driver: bridge